### PR TITLE
added appium 1.7.1 support

### PR DESCRIPTION
**Pull request by ajeeshvl**
Support for Appium v1.7.1.

### CODE REVIEW

**Comment by straiker** [comment]
any due date on when this will be merged?

**Comment by straiker** [comment]
can someone please take a look at this? AWS DF now suports 1.7.2 already

**Comment by ravuthlong** [comment]
Why is no one managing this repo?

**Comment by Portzt** [comment]
Does anyone know when this change will be merged in?   The latest version of Appium Python running in AWS is now 1.7.2.  The pull request reflects a simple string change for the fix and has been open since December of 2017.   I really like the idea of the plugin but it required that I dropped the version of selenium I ran so that I could not have errors using send_keys to an iOS device and it will require me to change other things about my testing to make it work correctly with other tests because I cannot select the correct version of Appium Python.   Based on the 3 previous comments for this thread the plugin doesn't appear to be actively maintained.   I hope that this is updated soon.

**Comment by nikhil-dabhade** [comment]
@Portzt Sorry for the delay on this. We are working on this merge request and this should be merged in by end of this week. It may require a few more days after that to release the official plugin.

**Comment by rvarum** [comment]
any updates on this one?

**Comment by nikhil-dabhade** [comment]
This has now been resolved.

**Pull request closed without merging**
