### PR TITLE
Update available Appium versions

### PR DESCRIPTION
**Pull request by martinschneider**
Set the available versions to 1.6.5, 1.7.1, 1.7.2

### CODE REVIEW

**Comment by Portzt** [comment]
Does anyone out there know when this can be merged in.    This pull request reflects all the current supported versions of Appium and looks like it would be more appropriate than PR #66 because it removes the deprecated versions of Appium.

**Comment by nikhil-dabhade** [comment]
@Portzt Sorry for the delay on this. We are working on this merge request and this should be merged in by end of this week. It may require a few more days after that to release the official plugin.

**Comment by Portzt** [comment]
Thank you for the quick reply.   I am excited to start using this for my
project or will make test automation so much easier.

**Comment by straiker** [comment]
@nikhil-dabhade when will the plugin be updated? the newest version of appium is now alreadi 1.8.1

**Comment by nikhil-dabhade** [comment]
This has been resolved.

**Pull request closed without merging**
