### PR TITLE
Jenkins Fixes…

### PR DESCRIPTION
**Pull request by anurag1408**
When ever we upload an app, Jenkins should wait till the upload status changes to succeed. However while waiting if for some reason , the thread was interrupted, we were breaking out and continuing with the execution. Since Schedule run expected the upload status as succeed, it was throwing exception that upload is not processed.

Similar issue was while waiting for the result from the run handler.
I have fixed both.

### CODE REVIEW

**Comment by ahawker** [comment]
If someone raises an InterruptException into the polling thread, you should NOT eat the exception and continue polling. My guess is, this happens when Jenkins is trying to stop the build and this won't let it die.

These calls should either allow the exception to propagate or you should handle the case in the return value so you know that the build should not continue.

**Comment by anurag1408** [comment]
As discussed, we are able to cancel the build while the thread is waiting for upload or run activity to complete.

**Comment by anurag1408** [comment]
Hi Hawker

you were correct. we should not swallow the interrupt exception. I have fixed this

**Comment by ahawker** [comment]
Merging in this PR.

As a note for the future, I'd like to see this ARN stuff get cleaned up. Either reworking the logic or encapsulating the shit under the covers of a class. We're doing inline string manipulation to build/modify these and the it's not clear from just reading the code what exactly is happening.

**Pull request merged**
